using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Assets.API.Pathfinding
{
    /// <summary>
    /// Diese Klasse ist nur ein Test um Git besser zu verstehen
    /// </summary>
    /// <autogeneratedoc />
    public class BranchDiffHelper
    {
    }
}
